[package]
name = "upack"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
rstest = "0.26"
fastrand = "2"
bytemuck = "1"

[features]
avx512 = []
avx2 = []
sse = []
neon = []
default = ["avx512", "avx2", "sse", "neon"]